IntelMQ 3.x compatibility
- allow setting the certbund_contact revision as environment variable INTELMQ_CERTBUND_CONTACT_REVISION
  for 3.x the branch intelmq-v3 is required INTELMQ_MAILGEN_REVISION
- allow setting the mailgen revision as environment variable
- webinput-csv-backend container: as the package intelmq is installed from PyPI here, we need to use the version on PyPI. intelmq's latest release is 3.0.2.post1 and thus unequal to the revision in the repository (3.0.2). Introduce a new environment variable INTELMQ_VERSION for this purpose
- only apply an import-path patch for intelmq_certbund_contact if we are not on 3.x
- intelmq_certbund_contact: with editable installations, installing a second intelmq package (for the intelmq/bots/experts/cerbund* structure) does not work. So we can work around by symlinking the files
- setup script for intelmq and intelmq_certbund_contact:
  - fix file permissions for installed configuration files
  - run configuration migration to convert the 2.x-style configuration to 3.x-style
  - and adapt the module names for certbund_contact and certbund_rules

fixes #13

diff --git a/intelmq/Dockerfile b/intelmq/Dockerfile
--- a/intelmq/Dockerfile
+++ b/intelmq/Dockerfile
@@ -3,10 +3,14 @@ FROM ubuntu:20.04
 ARG INTELMQ_REVISION
 ARG INTELMQ_API_REVISION
 ARG INTELMQ_MANAGER_REVISION
+ARG INTELMQ_CERTBUND_CONTACT_REVISION
+ARG INTELMQ_MAILGEN_REVISION
 
 ENV INTELMQ_REVISION ${INTELMQ_REVISION}
 ENV INTELMQ_API_REVISION ${INTELMQ_API_REVISION}
 ENV INTELMQ_MANAGER_REVISION ${INTELMQ_MANAGER_REVISION}
+ENV INTELMQ_CERTBUND_CONTACT_REVISION ${INTELMQ_CERTBUND_CONTACT_REVISION}
+ENV INTELMQ_MAILGEN_REVISION ${INTELMQ_MAILGEN_REVISION}
 
 RUN apt-get update && DEBIAN_FRONTEND="noninteractive" apt-get install -y apache2 libapache2-mod-wsgi-py3 cron
 
@@ -80,7 +84,7 @@ RUN git clone https://github.com/Intevation/intelmq-mailgen.git
 
 WORKDIR /opt/intelmq-mailgen
 
-RUN pip3 install -e .
+RUN git checkout $INTELMQ_MAILGEN_REVISION && pip3 install -e .
 
 WORKDIR /opt
 
@@ -92,9 +96,13 @@ WORKDIR /opt/intelmq-certbund-contact
 # Patch example rules to fix imports.
 COPY intelmq/import.patch .
 
-RUN patch -p 1 -i import.patch
+RUN git checkout $INTELMQ_CERTBUND_CONTACT_REVISION
+# if the condition is false, we don't want an exit code 1
+RUN bash -c "[ \"$INTELMQ_CERTBUND_CONTACT_REVISION\" != 'intelmq-v3' ] && patch -p 1 -i import.patch || :"
 
 RUN pip3 install -e .
+# with editable installations, installing a second intelmq package (for the intelmq/bots/experts/cerbund* structure) does not work. So we can work around by symlinking the files
+RUN bash -c "[ \"$INTELMQ_CERTBUND_CONTACT_REVISION\" == 'intelmq-v3' ] && cp -rs /opt/intelmq-certbund-contact/intelmq/bots/experts/certbund_rules /opt/intelmq/intelmq/bots/experts/ && cp -rs /opt/intelmq-certbund-contact/intelmq/bots/experts/certbund_contact /opt/intelmq/intelmq/bots/experts/ || :"
 
 RUN intelmq-api-adduser --user admin --password secret
 
